language: python
python: 2.7
sudo: false
cache:
  pip: true
  directories:
  - node_modules
before_install:
- nvm install 6.0.0
install:
- travis_retry pip install -r travis_requirements.txt
- paver install_libs
- travis_retry wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.40.zip
  -nv
- unzip -q google_appengine_1.9.40.zip
- export PYTHONPATH=${PYTHONPATH}:google_appengine
- travis_retry npm install
before_script:
- paver make
script:
- paver test
- npm test
- npm run lint -s
after_failure:
- cat test_failures.temp
before_deploy:
- echo "TODO: Ensure we should deploy this commit"
- openssl aes-256-cbc -K $encrypted_7463bcfc1880_key -iv $encrypted_7463bcfc1880_iv -in ops/deploy_keys.tar.enc -out ops/deploy_keys.tar -d
- ./ops/manage_deploy_keys -x
- paver make
deploy:
  skip_cleanup: true
  provider: gae
  keyfile: ops/tbatv-prod-hrd-deploy.json
  project: tbatv-prod-hrd
  version: prod-1
  config: "app.yaml app-backend-tasks-b2.yaml app-backend-tasks.yaml cron.yaml dispatch.yaml index.yaml queue.yaml"
  on:
    all_branches: true

